def patterncount(text, pattern):
    count = 0
    print(text[0:4])
    print(pattern)
    c=len(text)-len(pattern)
    print(c)
    for i in range(c):
        
        if text[i:i+len(pattern)]==pattern:
            count=count+1

    return count


y="TCACGTGGGTTGACGTGGGATCACGTGGGTACGTGGGACGTGGGAGACGTGGGGAACGTGGGATGATTAACGTGGGGCCAGTACGTGGGACGTGGGTACGTGGGCTAACGTGGGTCATGCTAGACGTGGGATACGTGGGTACGTGGGACGTGGGCACCACGTGGGACGTGGGACTACGTGGGACGTGGGACGTGGGCTCACGTGGGACGTGGGAAAACGTGGGCGACGTGGGGTCGTGTCACGTGGGACGTGGGAGGGACGTGGGACGTGGGGACGTGGGCCAACGTGGGACGTGGGCTACGTGGGTACACAGGCCACGTGGGTACGTGGGACGTGGGACGTGGGCACGTGGGACGTGGGTGACGTGGGACGTGGGAGACGTGGGAGGTATAAGCACGTGGGACGTGGGCTTCTTACGTGGGAGAATTTTGCACACGCACGTGGGACGTGGGACAACGTGGGACTAATGGACGTGGGAGCTCTTTACGTGGGAATGACGTGGGCAAAACGTGGGCACGTGGGACGTGGGTACGTGGGACGTGGGGGACGACGTGGGTAAGGGTTTACGTGGGGGACGTGGGGTCACCCGAACGTGGGGGGTGCGCCTTGTACGACGTGGGAACGTGGGACGTGGGCGGTTACGTGGGACGTGGGACGTGGGGACGTGGGACGTGGGTCTACGTGGGCACGTGGGTTACGTGGGGACGTGGGCACGTGGGGAACGTGGGTCCACGTGGGTGGACGTGGGACGTGGGTACGTGGGTACGTGGGACGTGGGACGTGGGGCAGGTACGTGGGTATTATACGTGGGGAACGTGGGGAAACGTGGGTGACGTGGGGGCCACGTGGGACGTGGGTACGTGGGACGTGGGACGTGGGGACGTGGGGATGACGTGGGCTGACGTGGGCGTAACGTGGGACGTGGGAGACGTGGGGTCTACGTGGGAACGTGGGAAACGTGGGTCAGACGTGGGACGTGGGAC"
x=patterncount(y,"ACGTGGGAC")
print(x)
        
